package com.HiWord9.RPRenames.util.config.generation;

import net.minecraft.entity.EntityType;

public class CEMList {
    public static final String[] models = new String[]{
            "allay", "armor_stand", "axolotl", "axolotl", "axolotl", "axolotl", "axolotl",
            "bat", "polar_bear", "bee", "bee", "bee", "bee", "bee", "blaze",
            "cat", "cat", "cat", "cat", "cat_collar", "cat", "ocelot", "cat", "cat", "cat", "cat", "cat", "cat",
            "chicken", "mooshroom", "cow", "mooshroom", "creeper", "creeper_charge", "dolphin", "enderman", "endermite",
            "cod", "puffer_fish_big", "puffer_fish_medium", "puffer_fish_small", "salmon", "tropical_fish_a", "tropical_fish_b",
            "fox", "fox", "fox", "fox", "frog", "frog", "frog", "ghast", "ghast", "goat", "guardian", "elder_guardian", "hoglin", "zoglin",
            "donkey", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse",
            "skeleton_horse", "horse", "zombie_horse", "mule",
            "evoker", "illusioner", "pillager", "ravager", "vex", "vex", "vindicator",
            "iron_golem", "llama", "llama", "llama", "llama",
            "panda", "panda", "panda", "panda", "panda", "panda", "panda",
            "parrot", "parrot", "parrot", "parrot", "parrot", "phantom", "pig", "piglin", "piglin_brute", "zombified_piglin",
            "rabbit", "rabbit", "rabbit", "rabbit", "rabbit", "rabbit", "rabbit",
            "sheep", "sheep_wool", "shulker", "silverfish", "skeleton", "stray", "wither_skeleton",
            "magma_cube", "slime", "sniffer", "snow_golem", "cave_spider", "spider", "glow_squid", "squid", "strider", "strider",
            "tadpole", "turtle",
            "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager",
            "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager",
            "villager", "villager", "villager", "wandering_trader",
            "warden", "witch", "wither", "wither_armor", "wither", "wolf", "wolf", "wolf_collar", "wolf",
            "drowned", "husk", "zombie",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager"
    };

    public static final String[] textures = new String[]{
            "allay/allay", "armorstand/wood",
            "axolotl/axolotl_blue", "axolotl/axolotl_cyan", "axolotl/axolotl_gold", "axolotl/axolotl_lucy", "axolotl/axolotl_wild",
            "bat", "bear/polarbear",
            "bee/bee", "bee/bee_angry", "bee/bee_angry_nectar", "bee/bee_nectar", "bee/bee_stinger", "blaze",
            "cat/all_black", "cat/black", "cat/british_shorthair", "cat/calico", "cat/cat_collar", "cat/jellie", "cat/ocelot",
            "cat/persian", "cat/ragdoll", "cat/red", "cat/siamese", "cat/tabby", "cat/white",
            "chicken", "cow/brown_mooshroom", "cow/cow", "cow/red_mooshroom", "creeper/creeper", "creeper/creeper_armor",
            "dolphin", "enderman/enderman", "endermite",
            "fish/cod", "fish/pufferfish", "fish/pufferfish", "fish/pufferfish", "fish/salmon", "fish/tropical_a", "fish/tropical_b",
            "fox/fox", "fox/fox_sleep", "fox/snow_fox", "fox/snow_fox_sleep",
            "frog/cold_frog", "frog/temperate_frog", "frog/warm_frog",
            "ghast/ghast", "ghast/ghast_shooting", "goat/goat", "guardian", "guardian_elder",
            "hoglin/hoglin", "hoglin/zoglin",
            "horse/donkey", "horse/horse_black", "horse/horse_brown", "horse/horse_chestnut", "horse/horse_creamy",
            "horse/horse_darkbrown", "horse/horse_gray", "horse/horse_markings_blackdots", "horse/horse_markings_white",
            "horse/horse_markings_whitedots", "horse/horse_markings_whitefield", "horse/horse_skeleton", "horse/horse_white",
            "horse/horse_zombie", "horse/mule",
            "illager/evoker", "illager/illusioner", "illager/pillager", "illager/ravager", "illager/vex", "illager/vex_charging",
            "illager/vindicator", "iron_golem/iron_golem",
            "llama/brown", "llama/creamy", "llama/gray", "llama/white",
            "panda/aggressive_panda", "panda/brown_panda", "panda/lazy_panda", "panda/panda",
            "panda/playful_panda", "panda/weak_panda", "panda/worried_panda",
            "parrot/parrot_blue", "parrot/parrot_green", "parrot/parrot_grey", "parrot/parrot_red_blue", "parrot/parrot_yellow_blue",
            "phantom", "pig/pig", "piglin/piglin", "piglin/piglin_brute", "piglin/zombified_piglin",
            "rabbit/black", "rabbit/brown", "rabbit/gold", "rabbit/salt", "rabbit/toast", "rabbit/white", "rabbit/white_splotched",
            "sheep/sheep", "sheep/sheep_fur", "shulker/shulker", "silverfish",
            "skeleton/skeleton", "skeleton/stray", "skeleton/wither_skeleton",
            "slime/magmacube", "slime/slime", "sniffer/sniffer", "snow_golem", "spider/cave_spider", "spider/spider", "squid/glow_squid", "squid/squid",
            "strider/strider", "strider/strider_cold", "tadpole/tadpole", "turtle/big_sea_turtle",
            "villager/profession/armorer", "villager/profession/butcher", "villager/profession/cartographer", "villager/profession/cleric",
            "villager/profession/farmer", "villager/profession/fisherman", "villager/profession/fletcher",
            "villager/profession/leatherworker", "villager/profession/librarian", "villager/profession/mason",
            "villager/profession/nitwit", "villager/profession/shepherd", "villager/profession/toolsmith",
            "villager/profession/weaponsmith", "villager/type/desert", "villager/type/jungle", "villager/type/plains",
            "villager/type/savanna", "villager/type/snow", "villager/type/swamp", "villager/type/taiga", "wandering_trader",
            "warden/warden", "witch", "wither/wither", "wither/wither_armor", "wither/wither_invulnerable",
            "wolf/wolf", "wolf/wolf_angry", "wolf/wolf_collar", "wolf/wolf_tame",
            "zombie/drowned", "zombie/husk", "zombie/zombie",
            "zombie_villager/profession/armorer", "zombie_villager/profession/butcher", "zombie_villager/profession/cartographer",
            "zombie_villager/profession/cleric", "zombie_villager/profession/farmer", "zombie_villager/profession/fisherman",
            "zombie_villager/profession/fletcher", "zombie_villager/profession/leatherworker", "zombie_villager/profession/librarian",
            "zombie_villager/profession/mason", "zombie_villager/profession/nitwit", "zombie_villager/profession/shepherd",
            "zombie_villager/profession/toolsmith", "zombie_villager/profession/weaponsmith", "zombie_villager/type/desert",
            "zombie_villager/type/jungle", "zombie_villager/type/plains", "zombie_villager/type/savanna", "zombie_villager/type/snow",
            "zombie_villager/type/swamp", "zombie_villager/type/taiga", "zombie_villager/zombie_villager"
    };

    public static final EntityType<?>[] mobs = new EntityType<?>[]{
            EntityType.ALLAY,
            EntityType.ARMOR_STAND,
            EntityType.AXOLOTL,
            EntityType.AXOLOTL,
            EntityType.AXOLOTL,
            EntityType.AXOLOTL,
            EntityType.AXOLOTL,
            EntityType.BAT,
            EntityType.POLAR_BEAR,
            EntityType.BEE,
            EntityType.BEE,
            EntityType.BEE,
            EntityType.BEE,
            EntityType.BEE,
            EntityType.BLAZE,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.OCELOT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CAT,
            EntityType.CHICKEN,
            EntityType.MOOSHROOM,
            EntityType.COW,
            EntityType.MOOSHROOM,
            EntityType.CREEPER,
            EntityType.CREEPER,
            EntityType.DOLPHIN,
            EntityType.ENDERMAN,
            EntityType.ENDERMITE,
            EntityType.COD,
            EntityType.PUFFERFISH,
            EntityType.PUFFERFISH,
            EntityType.PUFFERFISH,
            EntityType.SALMON,
            EntityType.TROPICAL_FISH,
            EntityType.TROPICAL_FISH,
            EntityType.FOX,
            EntityType.FOX,
            EntityType.FOX,
            EntityType.FOX,
            EntityType.FROG,
            EntityType.FROG,
            EntityType.FROG,
            EntityType.GHAST,
            EntityType.GHAST,
            EntityType.GOAT,
            EntityType.GUARDIAN,
            EntityType.ELDER_GUARDIAN,
            EntityType.HOGLIN,
            EntityType.ZOGLIN,
            EntityType.DONKEY,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.HORSE,
            EntityType.SKELETON_HORSE,
            EntityType.HORSE,
            EntityType.ZOMBIE_HORSE,
            EntityType.MULE,
            EntityType.EVOKER,
            EntityType.ILLUSIONER,
            EntityType.PILLAGER,
            EntityType.RAVAGER,
            EntityType.VEX,
            EntityType.VEX,
            EntityType.VINDICATOR,
            EntityType.IRON_GOLEM,
            EntityType.LLAMA,
            EntityType.LLAMA,
            EntityType.LLAMA,
            EntityType.LLAMA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PANDA,
            EntityType.PARROT,
            EntityType.PARROT,
            EntityType.PARROT,
            EntityType.PARROT,
            EntityType.PARROT,
            EntityType.PHANTOM,
            EntityType.PIG,
            EntityType.PIGLIN,
            EntityType.PIGLIN_BRUTE,
            EntityType.ZOMBIFIED_PIGLIN,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.RABBIT,
            EntityType.SHEEP,
            EntityType.SHEEP,
            EntityType.SHULKER,
            EntityType.SILVERFISH,
            EntityType.SKELETON,
            EntityType.STRAY,
            EntityType.WITHER_SKELETON,
            EntityType.MAGMA_CUBE,
            EntityType.SLIME,
            EntityType.SNIFFER,
            EntityType.SNOW_GOLEM,
            EntityType.CAVE_SPIDER,
            EntityType.SPIDER,
            EntityType.GLOW_SQUID,
            EntityType.SQUID,
            EntityType.STRIDER,
            EntityType.STRIDER,
            EntityType.TADPOLE,
            EntityType.TURTLE,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.VILLAGER,
            EntityType.WANDERING_TRADER,
            EntityType.WARDEN,
            EntityType.WITCH,
            EntityType.WITHER,
            EntityType.WITHER,
            EntityType.WITHER,
            EntityType.WOLF,
            EntityType.WOLF,
            EntityType.WOLF,
            EntityType.WOLF,
            EntityType.DROWNED,
            EntityType.HUSK,
            EntityType.ZOMBIE,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER,
            EntityType.ZOMBIE_VILLAGER
    };
}
