plugins {
	id 'maven-publish'
	id 'xyz.wagyourtail.unimined' version '1.4.2-SNAPSHOT'
	id "com.gradleup.shadow" version "9.4.1"
}

base {
	archivesName = "$project.archives_base_name-$project.minecraft_version"
}

version = project.mod_version
group = project.maven_group

repositories {
	unimined.neoForgedMaven()
	unimined.spongeMaven()
	unimined.wagYourMaven("snapshots")
	unimined.modrinthMaven()
	maven { url "https://maven.isxander.dev/releases/" }
	maven { url "https://maven.terraformersmc.com/releases/" }
}

configurations {
	shadow
}

sourceSets {
	fabric
	neoforge
}

unimined.minecraft {
	version project.minecraft_version

	fabric {
		loader fabric_loader_version
		accessWidener file("src/main/resources/${project.mod_id}.accesswidener")
	}

	defaultRemapJar = false
}

unimined.minecraft(sourceSets.fabric) {
	combineWith(sourceSets.main)

	fabric {
		loader fabric_loader_version
		accessWidener file("src/main/resources/${project.mod_id}.accesswidener")
	}

	defaultRemapJar = true
	defaultRemapSourcesJar = true
}

unimined.minecraft(sourceSets.neoforge) {
	combineWith(sourceSets.main)

	neoForge {
		loader("net.neoforged:neoforge:$project.neoforge_version")
		accessTransformer aw2at(file("src/main/resources/${project.mod_id}.accesswidener"))
	}

	minecraftRemapper.config {
		ignoreConflicts(true)
	}

	defaultRemapJar = true
	defaultRemapSourcesJar = true
}

dependencies {
	compileOnly "dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric"

	fabricImplementation "net.fabricmc:fabric-loader:${project.fabric_loader_version}"
	fabricImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	fabricImplementation "io.github.llamalad7:mixinextras-fabric:0.2.2"

	fabricImplementation "com.terraformersmc:modmenu:${project.modmenu_version}"
	fabricImplementation("dev.isxander:yet-another-config-lib:${project.yacl_version}-fabric") {
		exclude group: 'com.google.code.gson', module: 'gson'
	}

	neoforgeImplementation("dev.isxander:yet-another-config-lib:${project.yacl_version}-neoforge") {
		exclude group: 'com.google.code.gson', module: 'gson'
	}
}

shadowJar {
	configurations = [project.configurations.shadow]

	from(tasks.named("remapFabricJar").map { zipTree(it.archiveFile) })
	from(tasks.named("remapNeoforgeJar").map { zipTree(it.archiveFile) })

	archiveClassifier.set null
}

tasks.register("shadowSourcesJar", tasks.shadowJar.class as Class<Task>) {
	dependsOn("sourcesJar")
	configurations = [project.configurations.shadow]

	from(tasks.named("remapFabricSourcesJar").map { zipTree(it.archiveFile) })
	from(tasks.named("remapNeoforgeSourcesJar").map { zipTree(it.archiveFile) })

	archiveClassifier.set "sources"
}

[tasks.processResources, tasks.processFabricResources, tasks.processNeoforgeResources].each {
	def expandProps = [
			"version"                         : version,
			"group"                           : project.group, //Else we target the task's group.
			"mod_main_dir"                    : mod_main_dir,
			"mod_client_class"                : mod_client_class,
			"mod_modmenu_impl_subdir"         : mod_modmenu_impl_subdir,

			"fabric_version"                  : fabric_version,
			"fabric_loader_version"  		  : fabric_loader_version,

			"mod_id"                          : mod_id,
			"mod_name"                        : mod_name,
			"mod_description"                 : mod_description,
			"mod_author"                      : mod_author,

			"mod_homepage_modrinth"           : mod_homepage_modrinth,
			"mod_homepage_curseforge"         : mod_homepage_curseforge,
			"mod_donate_paypal"               : mod_donate_paypal,

			"mod_sources"                     : mod_sources,
			"mod_issue_tracker"               : mod_issue_tracker,
			"mod_license_link"                : mod_license_link,
			"mod_license"                     : mod_license,
			"mod_license_version"             : mod_license_version,

			"fabric_minecraft_version_range"  : fabric_minecraft_version_range,
			"fabric_loader_version_range"     : fabric_loader_version_range,
			"java_version"                    : java_version
	]
	it.filesMatching(['fabric.mod.json', 'META-INF/neoforge.mods.toml', mod_id + '.mixins.json']) {
		expand expandProps
	}
	it.inputs.properties(expandProps)
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.valueOf(java_version)
}

java {
	// generating sources
	withSourcesJar()
}

tasks.named("sourcesJar").configure {
	finalizedBy("shadowSourcesJar")
}

jar {
	from("LICENSE") {
		rename { "${it}_${base.archivesName}"}
	}
}