# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Mod Properties
	mod_id = rprenames
	mod_version = 0.12.0

	mod_name = RP Renames
	mod_description = View all Resource Pack Renames in a new anvil GUI catalog!
	mod_author = HiWord9

	mod_homepage_modrinth = https://modrinth.com/mod/rp-renames
	mod_homepage_curseforge = https://www.curseforge.com/minecraft/mc-mods/rp-renames
	mod_donate_paypal = https://paypal.me/hiword9

	mod_sources = https://github.com/HiWord9/RPRenames
	mod_issue_tracker = https://github.com/HiWord9/RPRenames/issues

	mod_license = Team Durt License
	mod_license_link = https://license.durt.team
	mod_license_version = 1.0

	mod_main_dir = com.hiword9.rprenames
	mod_client_class = RPRenames
	mod_modmenu_impl_subdir = config.ModMenuIntegration

	maven_group = com.hiword9
	archives_base_name = RPRenames

# fabric
	fabric_loader_version_range = >=0.14.22
	fabric_minecraft_version_range = >=26.2
	fabric_loader_version = 0.18.4

# neoforge
	neoforge_loader_version = 11.0.6

# Dependencies
	minecraft_version = 26.2
	fabric_version = 0.153.0+26.2
	neoforge_version = 26.2.0.7-beta
	modmenu_version = 20.0.0-beta.4
	yacl_version = 3.9.5+26.2

	java_version = 25