package com.HiWord9.RPRenames;

import net.minecraft.entity.EntityType;
import net.minecraft.item.Item;
import net.minecraft.item.Items;

public class CEM {
    public static String[] models = new String[]{
            "allay", "armor_stand", "axolotl", "axolotl", "axolotl", "axolotl", "axolotl",
            "bat", "polar_bear", "bee", "bee", "bee", "bee", "bee", "blaze",
            "cat", "cat", "cat", "cat", "cat_collar", "cat", "ocelot", "cat", "cat", "cat", "cat", "cat", "cat",
            "chicken", "mooshroom", "cow", "mooshroom", "creeper", "creeper_charge", "dolphin", "enderman", "endermite",
            "cod", "puffer_fish_big", "puffer_fish_medium", "puffer_fish_small", "salmon", "tropical_fish_a", "tropical_fish_b",
            "fox", "fox", "fox", "fox", "frog", "frog", "frog", "ghast", "ghast", "goat", "guardian", "elder_guardian", "hoglin", "zoglin",
            "donkey", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse", "horse",
            "skeleton_horse", "horse", "zombie_horse", "mule",
            "evoker", "illusioner", "pillager", "ravager", "vex", "vex", "vindicator",
            "iron_golem", "llama", "llama", "llama", "llama",
            "panda", "panda", "panda", "panda", "panda", "panda", "panda",
            "parrot", "parrot", "parrot", "parrot", "parrot", "phantom", "pig", "piglin", "piglin_brute", "zombified_piglin",
            "rabbit", "rabbit", "rabbit", "rabbit", "rabbit", "rabbit", "rabbit",
            "sheep", "sheep_wool", "shulker", "silverfish", "skeleton", "stray", "wither_skeleton",
            "magma_cube", "slime", "snow_golem", "cave_spider", "spider", "glow_squid", "squid", "strider", "strider",
            "tadpole", "turtle",
            "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager",
            "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager", "villager",
            "villager", "villager", "villager", "wandering_trader",
            "warden", "witch", "wither", "wither_armor", "wither", "wolf", "wolf", "wolf_collar", "wolf",
            "drowned", "husk", "zombie",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager",
            "zombie_villager", "zombie_villager", "zombie_villager", "zombie_villager"
    };

    public static String[] textures = new String[]{
            "allay/allay", "armorstand/wood",
            "axolotl/axolotl_blue", "axolotl/axolotl_cyan", "axolotl/axolotl_gold", "axolotl/axolotl_lucy", "axolotl/axolotl_wild",
            "bat", "bear/polarbear",
            "bee/bee", "bee/bee_angry", "bee/bee_angry_nectar", "bee/bee_nectar", "bee/bee_stinger", "blaze",
            "cat/all_black", "cat/black", "cat/british_shorthair", "cat/calico", "cat/cat_collar", "cat/jellie", "cat/ocelot",
            "cat/persian", "cat/ragdoll", "cat/red", "cat/siamese", "cat/tabby", "cat/white",
            "chicken", "cow/brown_mooshroom", "cow/cow", "cow/red_mooshroom", "creeper/creeper", "creeper/creeper_armor",
            "dolphin", "enderman/enderman", "endermite",
            "fish/cod", "fish/pufferfish", "fish/pufferfish", "fish/pufferfish", "fish/salmon", "fish/tropical_a", "fish/tropical_b",
            "fox/fox", "fox/fox_sleep", "fox/snow_fox", "fox/snow_fox_sleep",
            "frog/cold_frog", "frog/temperate_frog", "frog/warm_frog",
            "ghast/ghast", "ghast/ghast_shooting", "goat/goat", "guardian", "guardian_elder",
            "hoglin/hoglin", "hoglin/zoglin",
            "horse/donkey", "horse/horse_black", "horse/horse_brown", "horse/horse_chestnut", "horse/horse_creamy",
            "horse/horse_darkbrown", "horse/horse_gray", "horse/horse_markings_blackdots", "horse/horse_markings_white",
            "horse/horse_markings_whitedots", "horse/horse_markings_whitefield", "horse/horse_skeleton", "horse/horse_white",
            "horse/horse_zombie", "horse/mule",
            "illager/evoker", "illager/illusioner", "illager/pillager", "illager/ravager", "illager/vex", "illager/vex_charging",
            "illager/vindicator", "iron_golem/iron_golem",
            "llama/brown", "llama/creamy", "llama/gray", "llama/white",
            "panda/aggressive_panda", "panda/brown_panda", "panda/lazy_panda", "panda/panda",
            "panda/playful_panda", "panda/weak_panda", "panda/worried_panda",
            "parrot/parrot_blue", "parrot/parrot_green", "parrot/parrot_grey", "parrot/parrot_red_blue", "parrot/parrot_yellow_blue",
            "phantom", "pig/pig", "piglin/piglin", "piglin/piglin_brute", "piglin/zombified_piglin",
            "rabbit/black", "rabbit/brown", "rabbit/gold", "rabbit/salt", "rabbit/toast", "rabbit/white", "rabbit/white_splotched",
            "sheep/sheep", "sheep/sheep_fur", "shulker/shulker", "silverfish",
            "skeleton/skeleton", "skeleton/stray", "skeleton/wither_skeleton",
            "slime/magmacube", "slime/slime", "snow_golem", "spider/cave_spider", "spider/spider", "squid/glow_squid", "squid/squid",
            "strider/strider", "strider/strider_cold", "tadpole/tadpole", "turtle/big_sea_turtle",
            "villager/profession/armorer", "villager/profession/butcher", "villager/profession/cartographer", "villager/profession/cleric",
            "villager/profession/farmer", "villager/profession/fisherman", "villager/profession/fletcher",
            "villager/profession/leatherworker", "villager/profession/librarian", "villager/profession/mason",
            "villager/profession/nitwit", "villager/profession/shepherd", "villager/profession/toolsmith",
            "villager/profession/weaponsmith", "villager/type/desert", "villager/type/jungle", "villager/type/plains",
            "villager/type/savanna", "villager/type/snow", "villager/type/swamp", "villager/type/taiga", "wandering_trader",
            "warden/warden", "witch", "wither/wither", "wither/wither_armor", "wither/wither_invulnerable",
            "wolf/wolf", "wolf/wolf_angry", "wolf/wolf_collar", "wolf/wolf_tame",
            "zombie/drowned", "zombie/husk", "zombie/zombie",
            "zombie_villager/profession/armorer", "zombie_villager/profession/butcher", "zombie_villager/profession/cartographer",
            "zombie_villager/profession/cleric", "zombie_villager/profession/farmer", "zombie_villager/profession/fisherman",
            "zombie_villager/profession/fletcher", "zombie_villager/profession/leatherworker", "zombie_villager/profession/librarian",
            "zombie_villager/profession/mason", "zombie_villager/profession/nitwit", "zombie_villager/profession/shepherd",
            "zombie_villager/profession/toolsmith", "zombie_villager/profession/weaponsmith", "zombie_villager/type/desert",
            "zombie_villager/type/jungle", "zombie_villager/type/plains", "zombie_villager/type/savanna", "zombie_villager/type/snow",
            "zombie_villager/type/swamp", "zombie_villager/type/taiga", "zombie_villager/zombie_villager"
    };

    public static String[] mobsNames = new String[]{
            EntityType.ALLAY.getUntranslatedName(),
            EntityType.ARMOR_STAND.getUntranslatedName(),
            EntityType.AXOLOTL.getUntranslatedName(),
            EntityType.AXOLOTL.getUntranslatedName(),
            EntityType.AXOLOTL.getUntranslatedName(),
            EntityType.AXOLOTL.getUntranslatedName(),
            EntityType.AXOLOTL.getUntranslatedName(),
            EntityType.BAT.getUntranslatedName(),
            EntityType.POLAR_BEAR.getUntranslatedName(),
            EntityType.BEE.getUntranslatedName(),
            EntityType.BEE.getUntranslatedName(),
            EntityType.BEE.getUntranslatedName(),
            EntityType.BEE.getUntranslatedName(),
            EntityType.BEE.getUntranslatedName(),
            EntityType.BLAZE.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.OCELOT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CAT.getUntranslatedName(),
            EntityType.CHICKEN.getUntranslatedName(),
            EntityType.MOOSHROOM.getUntranslatedName(),
            EntityType.COW.getUntranslatedName(),
            EntityType.MOOSHROOM.getUntranslatedName(),
            EntityType.CREEPER.getUntranslatedName(),
            EntityType.CREEPER.getUntranslatedName(),
            EntityType.DOLPHIN.getUntranslatedName(),
            EntityType.ENDERMAN.getUntranslatedName(),
            EntityType.ENDERMITE.getUntranslatedName(),
            EntityType.COD.getUntranslatedName(),
            EntityType.PUFFERFISH.getUntranslatedName(),
            EntityType.PUFFERFISH.getUntranslatedName(),
            EntityType.PUFFERFISH.getUntranslatedName(),
            EntityType.SALMON.getUntranslatedName(),
            EntityType.TROPICAL_FISH.getUntranslatedName(),
            EntityType.TROPICAL_FISH.getUntranslatedName(),
            EntityType.FOX.getUntranslatedName(),
            EntityType.FOX.getUntranslatedName(),
            EntityType.FOX.getUntranslatedName(),
            EntityType.FOX.getUntranslatedName(),
            EntityType.FROG.getUntranslatedName(),
            EntityType.FROG.getUntranslatedName(),
            EntityType.FROG.getUntranslatedName(),
            EntityType.GHAST.getUntranslatedName(),
            EntityType.GHAST.getUntranslatedName(),
            EntityType.GOAT.getUntranslatedName(),
            EntityType.GUARDIAN.getUntranslatedName(),
            EntityType.ELDER_GUARDIAN.getUntranslatedName(),
            EntityType.HOGLIN.getUntranslatedName(),
            EntityType.ZOGLIN.getUntranslatedName(),
            EntityType.DONKEY.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.SKELETON_HORSE.getUntranslatedName(),
            EntityType.HORSE.getUntranslatedName(),
            EntityType.ZOMBIE_HORSE.getUntranslatedName(),
            EntityType.MULE.getUntranslatedName(),
            EntityType.EVOKER.getUntranslatedName(),
            EntityType.ILLUSIONER.getUntranslatedName(),
            EntityType.PILLAGER.getUntranslatedName(),
            EntityType.RAVAGER.getUntranslatedName(),
            EntityType.VEX.getUntranslatedName(),
            EntityType.VEX.getUntranslatedName(),
            EntityType.VINDICATOR.getUntranslatedName(),
            EntityType.IRON_GOLEM.getUntranslatedName(),
            EntityType.LLAMA.getUntranslatedName(),
            EntityType.LLAMA.getUntranslatedName(),
            EntityType.LLAMA.getUntranslatedName(),
            EntityType.LLAMA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PANDA.getUntranslatedName(),
            EntityType.PARROT.getUntranslatedName(),
            EntityType.PARROT.getUntranslatedName(),
            EntityType.PARROT.getUntranslatedName(),
            EntityType.PARROT.getUntranslatedName(),
            EntityType.PARROT.getUntranslatedName(),
            EntityType.PHANTOM.getUntranslatedName(),
            EntityType.PIG.getUntranslatedName(),
            EntityType.PIGLIN.getUntranslatedName(),
            EntityType.PIGLIN_BRUTE.getUntranslatedName(),
            EntityType.ZOMBIFIED_PIGLIN.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.RABBIT.getUntranslatedName(),
            EntityType.SHEEP.getUntranslatedName(),
            EntityType.SHEEP.getUntranslatedName(),
            EntityType.SHULKER.getUntranslatedName(),
            EntityType.SILVERFISH.getUntranslatedName(),
            EntityType.SKELETON.getUntranslatedName(),
            EntityType.STRAY.getUntranslatedName(),
            EntityType.WITHER_SKELETON.getUntranslatedName(),
            EntityType.MAGMA_CUBE.getUntranslatedName(),
            EntityType.SLIME.getUntranslatedName(),
            EntityType.SNOW_GOLEM.getUntranslatedName(),
            EntityType.CAVE_SPIDER.getUntranslatedName(),
            EntityType.SPIDER.getUntranslatedName(),
            EntityType.GLOW_SQUID.getUntranslatedName(),
            EntityType.SQUID.getUntranslatedName(),
            EntityType.STRIDER.getUntranslatedName(),
            EntityType.STRIDER.getUntranslatedName(),
            EntityType.TADPOLE.getUntranslatedName(),
            EntityType.TURTLE.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.VILLAGER.getUntranslatedName(),
            EntityType.WANDERING_TRADER.getUntranslatedName(),
            EntityType.WARDEN.getUntranslatedName(),
            EntityType.WITCH.getUntranslatedName(),
            EntityType.WITHER.getUntranslatedName(),
            EntityType.WITHER.getUntranslatedName(),
            EntityType.WITHER.getUntranslatedName(),
            EntityType.WOLF.getUntranslatedName(),
            EntityType.WOLF.getUntranslatedName(),
            EntityType.WOLF.getUntranslatedName(),
            EntityType.WOLF.getUntranslatedName(),
            EntityType.DROWNED.getUntranslatedName(),
            EntityType.HUSK.getUntranslatedName(),
            EntityType.ZOMBIE.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName(),
            EntityType.ZOMBIE_VILLAGER.getUntranslatedName()
    };

    public static Item[] spawnEggItems = new Item[]{
            Items.ALLAY_SPAWN_EGG,
            Items.ARMOR_STAND,
            Items.AXOLOTL_SPAWN_EGG,
            Items.AXOLOTL_SPAWN_EGG,
            Items.AXOLOTL_SPAWN_EGG,
            Items.AXOLOTL_SPAWN_EGG,
            Items.AXOLOTL_SPAWN_EGG,
            Items.BAT_SPAWN_EGG,
            Items.POLAR_BEAR_SPAWN_EGG,
            Items.BEE_SPAWN_EGG,
            Items.BEE_SPAWN_EGG,
            Items.BEE_SPAWN_EGG,
            Items.BEE_SPAWN_EGG,
            Items.BEE_SPAWN_EGG,
            Items.BLAZE_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.OCELOT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CAT_SPAWN_EGG,
            Items.CHICKEN_SPAWN_EGG,
            Items.MOOSHROOM_SPAWN_EGG,
            Items.COW_SPAWN_EGG,
            Items.MOOSHROOM_SPAWN_EGG,
            Items.CREEPER_SPAWN_EGG,
            Items.CREEPER_SPAWN_EGG,
            Items.DOLPHIN_SPAWN_EGG,
            Items.ENDERMAN_SPAWN_EGG,
            Items.ENDERMITE_SPAWN_EGG,
            Items.COD_SPAWN_EGG,
            Items.PUFFERFISH_SPAWN_EGG,
            Items.PUFFERFISH_SPAWN_EGG,
            Items.PUFFERFISH_SPAWN_EGG,
            Items.SALMON_SPAWN_EGG,
            Items.TROPICAL_FISH_SPAWN_EGG,
            Items.TROPICAL_FISH_SPAWN_EGG,
            Items.FOX_SPAWN_EGG,
            Items.FOX_SPAWN_EGG,
            Items.FOX_SPAWN_EGG,
            Items.FOX_SPAWN_EGG,
            Items.FROG_SPAWN_EGG,
            Items.FROG_SPAWN_EGG,
            Items.FROG_SPAWN_EGG,
            Items.GHAST_SPAWN_EGG,
            Items.GHAST_SPAWN_EGG,
            Items.GOAT_SPAWN_EGG,
            Items.GUARDIAN_SPAWN_EGG,
            Items.ELDER_GUARDIAN_SPAWN_EGG,
            Items.HOGLIN_SPAWN_EGG,
            Items.ZOGLIN_SPAWN_EGG,
            Items.DONKEY_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.SKELETON_HORSE_SPAWN_EGG,
            Items.HORSE_SPAWN_EGG,
            Items.ZOMBIE_HORSE_SPAWN_EGG,
            Items.MULE_SPAWN_EGG,
            Items.EVOKER_SPAWN_EGG,
            Items.STRUCTURE_VOID,
            Items.PILLAGER_SPAWN_EGG,
            Items.RAVAGER_SPAWN_EGG,
            Items.VEX_SPAWN_EGG,
            Items.VEX_SPAWN_EGG,
            Items.VINDICATOR_SPAWN_EGG,
            Items.IRON_BLOCK,
            Items.LLAMA_SPAWN_EGG,
            Items.LLAMA_SPAWN_EGG,
            Items.LLAMA_SPAWN_EGG,
            Items.LLAMA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PANDA_SPAWN_EGG,
            Items.PARROT_SPAWN_EGG,
            Items.PARROT_SPAWN_EGG,
            Items.PARROT_SPAWN_EGG,
            Items.PARROT_SPAWN_EGG,
            Items.PARROT_SPAWN_EGG,
            Items.PHANTOM_SPAWN_EGG,
            Items.PIG_SPAWN_EGG,
            Items.PIGLIN_SPAWN_EGG,
            Items.PIGLIN_BRUTE_SPAWN_EGG,
            Items.ZOMBIFIED_PIGLIN_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.RABBIT_SPAWN_EGG,
            Items.SHEEP_SPAWN_EGG,
            Items.SHEEP_SPAWN_EGG,
            Items.SHULKER_SPAWN_EGG,
            Items.SILVERFISH_SPAWN_EGG,
            Items.SKELETON_SPAWN_EGG,
            Items.STRAY_SPAWN_EGG,
            Items.WITHER_SKELETON_SPAWN_EGG,
            Items.MAGMA_CUBE_SPAWN_EGG,
            Items.SLIME_SPAWN_EGG,
            Items.SNOW_BLOCK,
            Items.CAVE_SPIDER_SPAWN_EGG,
            Items.SPIDER_SPAWN_EGG,
            Items.GLOW_SQUID_SPAWN_EGG,
            Items.SQUID_SPAWN_EGG,
            Items.STRIDER_SPAWN_EGG,
            Items.STRIDER_SPAWN_EGG,
            Items.TADPOLE_SPAWN_EGG,
            Items.TURTLE_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.VILLAGER_SPAWN_EGG,
            Items.WANDERING_TRADER_SPAWN_EGG,
            Items.WARDEN_SPAWN_EGG,
            Items.WITCH_SPAWN_EGG,
            Items.SOUL_SAND,
            Items.SOUL_SAND,
            Items.SOUL_SAND,
            Items.WOLF_SPAWN_EGG,
            Items.WOLF_SPAWN_EGG,
            Items.WOLF_SPAWN_EGG,
            Items.WOLF_SPAWN_EGG,
            Items.DROWNED_SPAWN_EGG,
            Items.HUSK_SPAWN_EGG,
            Items.ZOMBIE_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG,
            Items.ZOMBIE_VILLAGER_SPAWN_EGG
    };
}
