package com.hiword9.rprenames.mod.config;

import com.hiword9.rprenames.mod.RPRenames;
import com.hiword9.rprenames.mod.gui.widget.external.FavoriteButton;
import com.hiword9.rprenames.api.ext.rename.renderer.PreviewTooltipPositioner;
import dev.isxander.yacl3.api.*;
import dev.isxander.yacl3.api.controller.*;
import net.minecraft.ChatFormatting;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.network.chat.Component;
import net.minecraft.network.chat.Style;

import java.awt.Color;

public class ModConfigScreenFactory {
    public static Screen create(Screen parent) {
        ModConfig currentConfig = ModConfig.INSTANCE, defaultConfig = new ModConfig();

        return YetAnotherConfigLib.createBuilder()
            .title(Component.translatable("rprenames.config.title"))
            .save(currentConfig::write)
            .category(ConfigCategory.createBuilder()
                .name(Component.translatable("rprenames.config.general"))
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.general.ignoreCEM"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.general.ignoreCEM.tooltip")))
                    .binding(defaultConfig.ignoreCEM, () -> currentConfig.ignoreCEM, currentConfig::setIgnoreCEM)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.general.enableAnvilModification"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.general.enableAnvilModification.tooltip")))
                    .binding(defaultConfig.enableAnvilModification, () -> currentConfig.enableAnvilModification, val -> currentConfig.enableAnvilModification = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.general.loadModBuiltinResources"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.general.loadModBuiltinResources.tooltip")))
                    .binding(defaultConfig.loadModBuiltinResources, () -> currentConfig.loadModBuiltinResources, val -> currentConfig.loadModBuiltinResources = val)
                    .controller(TickBoxControllerBuilder::create)
                    .flag(OptionFlag.GAME_RESTART)
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.general.creativeTabCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.general.creativeTabCategory.compareItemGroupRenames"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.general.creativeTabCategory.compareItemGroupRenames.tooltip")))
                        .binding(defaultConfig.compareItemGroupRenames, () -> currentConfig.compareItemGroupRenames, currentConfig::setCompareItemGroupRenames)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.general.creativeTabCategory.generateSpawnEggsInItemGroup"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.general.creativeTabCategory.generateSpawnEggsInItemGroup.tooltip")))
                        .binding(defaultConfig.generateSpawnEggsInItemGroup, () -> currentConfig.generateSpawnEggsInItemGroup, currentConfig::setGenerateSpawnEggsInItemGroup)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .build())
            .category(ConfigCategory.createBuilder()
                .name(Component.translatable("rprenames.config.gui"))
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.gui.openByDefault"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.gui.openByDefault.tooltip")))
                    .binding(defaultConfig.openByDefault, () -> currentConfig.openByDefault, val -> currentConfig.openByDefault = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.gui.offsetMenu"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.gui.offsetMenu.tooltip")))
                    .binding(defaultConfig.offsetMenu, () -> currentConfig.offsetMenu, val -> currentConfig.offsetMenu = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<FavoriteButton.Position>createBuilder()
                    .name(Component.translatable("rprenames.config.gui.favoriteButtonPosition"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.gui.favoriteButtonPosition.tooltip")))
                    .binding(defaultConfig.favoriteButtonPosition, () -> currentConfig.favoriteButtonPosition, val -> currentConfig.favoriteButtonPosition = val)
                    .controller(opt -> EnumControllerBuilder.create(opt)
                        .enumClass(FavoriteButton.Position.class)
                        .formatValue(value -> Component.translatable("rprenames.config.gui.favoriteButtonPosition." + value.name())))
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.tooltipCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.tooltipCategory.showPackName"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.tooltipCategory.showPackName.tooltip")))
                        .binding(defaultConfig.showPackName, () -> currentConfig.showPackName, val -> currentConfig.showPackName = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.tooltipCategory.showExtraProperties"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.tooltipCategory.showExtraProperties.tooltip")))
                        .binding(defaultConfig.showExtraProperties, () -> currentConfig.showExtraProperties, val -> currentConfig.showExtraProperties = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.tooltipCategory.tooltipSlotCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.tooltipCategory.slotCategory.highlightTooltipSlotWrong"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.tooltipCategory.slotCategory.highlightTooltipSlotWrong.tooltip")))
                        .binding(defaultConfig.highlightTooltipSlotWrong, () -> currentConfig.highlightTooltipSlotWrong, val -> currentConfig.highlightTooltipSlotWrong = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.tooltipCategory.slotCategory.highlightTooltipSlotSelected"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.tooltipCategory.slotCategory.highlightTooltipSlotSelected.tooltip")))
                        .binding(defaultConfig.highlightTooltipSlotSelected, () -> currentConfig.highlightTooltipSlotSelected, val -> currentConfig.highlightTooltipSlotSelected = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.renderCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.highlightSelected"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.highlightSelected.tooltip")))
                        .binding(defaultConfig.highlightSelected, () -> currentConfig.highlightSelected, val -> currentConfig.highlightSelected = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.recolorFavoriteTooltip"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.recolorFavoriteTooltip.tooltip")))
                        .binding(defaultConfig.recolorFavoriteTooltip, () -> currentConfig.recolorFavoriteTooltip, val -> currentConfig.recolorFavoriteTooltip = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.renderStarInFavoriteTooltip"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.renderStarInFavoriteTooltip.tooltip")))
                        .binding(defaultConfig.renderStarInFavoriteTooltip, () -> currentConfig.renderStarInFavoriteTooltip, val -> currentConfig.renderStarInFavoriteTooltip = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.highlightSlot"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.highlightSlot.tooltip")))
                        .binding(defaultConfig.highlightSlot, () -> currentConfig.highlightSlot, val -> currentConfig.highlightSlot = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory"))
                    .option(Option.<Color>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory.slotHighlightColor"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory.slotHighlightColor.tooltip")))
                        .binding(new Color(defaultConfig.slotHighlightColorRGB), () -> new Color(currentConfig.slotHighlightColorRGB), val -> currentConfig.slotHighlightColorRGB = val.getRGB() & 0xFFFFFF)
                        .controller(ColorControllerBuilder::create)
                        .build())
                    .option(Option.<Integer>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory.slotHighlightALPHA"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory.slotHighlightALPHA.tooltip")))
                        .binding(defaultConfig.slotHighlightColorALPHA, () -> currentConfig.slotHighlightColorALPHA, val -> currentConfig.slotHighlightColorALPHA = val)
                        .controller(opt -> IntegerSliderControllerBuilder.create(opt)
                            .range(0, 100)
                            .step(1)
                            .formatValue(percent -> percent == 0
                                ? Component.translatable("rprenames.config.gui.renderCategory.slotHighlightColorCategory.slotHighlightALPHA.off").withStyle(ChatFormatting.RED)
                                : Component.literal(percent.toString())))
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.previewCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.enablePreview"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.enablePreview.tooltip")))
                        .binding(defaultConfig.enablePreview, () -> currentConfig.enablePreview, val -> currentConfig.enablePreview = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<PreviewTooltipPositioner.PreviewPos>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.previewPos"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.previewPos.tooltip")))
                        .binding(defaultConfig.previewPos, () -> currentConfig.previewPos, val -> currentConfig.previewPos = val)
                        .controller(opt -> EnumControllerBuilder.create(opt)
                            .enumClass(PreviewTooltipPositioner.PreviewPos.class)
                            .formatValue(value -> Component.translatable("rprenames.config.gui.previewCategory.previewPos." + value.name())))
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.previewCategory.previewScaleCategory"))
                    .option(Option.<Double>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.scaleCategory.scaleFactorItem"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.scaleCategory.scaleFactorItem.tooltip")))
                        .binding(defaultConfig.scaleFactorItem, () -> currentConfig.scaleFactorItem, val -> currentConfig.scaleFactorItem = val)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                    .option(Option.<Double>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.scaleCategory.scaleFactorEntity"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.scaleCategory.scaleFactorEntity.tooltip")))
                        .binding(defaultConfig.scaleFactorEntity, () -> currentConfig.scaleFactorEntity, val -> currentConfig.scaleFactorEntity = val)
                        .controller(DoubleFieldControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.previewCategory.playerCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.playerPreviewByDefault"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.playerPreviewByDefault.tooltip")))
                        .binding(defaultConfig.playerPreviewByDefault, () -> currentConfig.playerPreviewByDefault, val -> currentConfig.playerPreviewByDefault = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.spinPlayerPreview"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.spinPlayerPreview.tooltip")))
                        .binding(defaultConfig.spinPlayerPreview, () -> currentConfig.spinPlayerPreview, val -> currentConfig.spinPlayerPreview = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.alwaysAllowPlayerPreviewHead"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.playerCategory.alwaysAllowPlayerPreviewHead.tooltip")))
                        .binding(defaultConfig.alwaysAllowPlayerPreviewHead, () -> currentConfig.alwaysAllowPlayerPreviewHead, val -> currentConfig.alwaysAllowPlayerPreviewHead = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.previewCategory.entityCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.entityCategory.spinMobPreview"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.entityCategory.spinMobPreview.tooltip")))
                        .binding(defaultConfig.spinMobPreview, () -> currentConfig.spinMobPreview, val -> currentConfig.spinMobPreview = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.previewCategory.entityCategory.disableSnowGolemPumpkin"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.previewCategory.entityCategory.disableSnowGolemPumpkin.tooltip")))
                        .binding(defaultConfig.disableSnowGolemPumpkin, () -> currentConfig.disableSnowGolemPumpkin, val -> currentConfig.disableSnowGolemPumpkin = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .group(OptionGroup.createBuilder()
                    .name(Component.translatable("rprenames.config.gui.hintsCategory"))
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.hintsCategory.disableTooltipHints"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.hintsCategory.disableTooltipHints.tooltip")))
                        .binding(defaultConfig.disableTooltipHints, () -> currentConfig.disableTooltipHints, val -> currentConfig.disableTooltipHints = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .option(Option.<Boolean>createBuilder()
                        .name(Component.translatable("rprenames.config.gui.hintsCategory.disablePageArrowsHints"))
                        .description(OptionDescription.of(Component.translatable("rprenames.config.gui.hintsCategory.disablePageArrowsHints.tooltip")))
                        .binding(defaultConfig.disablePageArrowsHints, () -> currentConfig.disablePageArrowsHints, val -> currentConfig.disablePageArrowsHints = val)
                        .controller(TickBoxControllerBuilder::create)
                        .build())
                    .build())
                .build())
            .category(ConfigCategory.createBuilder()
                .name(Component.translatable("rprenames.config.debug"))
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.debug.updateConfig"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.updateConfig.tooltip")))
                    .binding(defaultConfig.updateConfig, () -> currentConfig.updateConfig, val -> currentConfig.updateConfig = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(ButtonOption.createBuilder()
                    .name(Component.translatable("rprenames.config.debug.recreateConfig"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.recreateConfig.tooltip")))
                    .action((yaclScreen, option) -> {
                        RPRenames.LOGGER.info("Recreating config manually");
                        RPRenames.updatableRenamesManager.updateRenames();
                        currentConfig.shouldUpdateItemGroup = true;
                    })
                    .text(Component.translatable("rprenames.config.debug.recreateConfig.title").withStyle(Style.EMPTY.withColor(ChatFormatting.GOLD)))
                    .build())
                .option(ButtonOption.createBuilder()
                    .name(Component.translatable("rprenames.config.debug.clearConfig"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.clearConfig.tooltip")))
                    .action((yaclScreen, option) -> {
                        RPRenames.LOGGER.info("Deleting config manually");
                        RPRenames.updatableRenamesManager.clearRenames();
                        currentConfig.shouldUpdateItemGroup = true;
                    })
                    .text(Component.translatable("rprenames.config.debug.clearConfig.title").withStyle(Style.EMPTY.withColor(ChatFormatting.RED)))
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.debug.showNbtDisplayName"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.showNbtDisplayName.tooltip")))
                    .binding(defaultConfig.showNamePattern, () -> currentConfig.showNamePattern, val -> currentConfig.showNamePattern = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.debug.showOriginalProperties"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.showOriginalProperties.tooltip")))
                    .binding(defaultConfig.showOriginalProperties, () -> currentConfig.showOriginalProperties, val -> currentConfig.showOriginalProperties = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .option(Option.<Boolean>createBuilder()
                    .name(Component.translatable("rprenames.config.debug.fixDelayedPacketsChangingTab"))
                    .description(OptionDescription.of(Component.translatable("rprenames.config.debug.fixDelayedPacketsChangingTab.tooltip")))
                    .binding(defaultConfig.fixDelayedPacketsChangingTab, () -> currentConfig.fixDelayedPacketsChangingTab, val -> currentConfig.fixDelayedPacketsChangingTab = val)
                    .controller(TickBoxControllerBuilder::create)
                    .build())
                .build())
            .build()
            .generateScreen(parent);
    }
}
